import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Rajdhani, Saira, Saira_Stencil_One } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";
import { Toaster } from "sonner"
import { AuthProvider } from "@/context/auth-context";
import { CartProvider } from "@/context/cart-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const fontTitle = Rajdhani({
  subsets: ['latin'],
  weight: ['500', '600', '700'],
  variable: '--font-title',
});

const fontBody = Inter({
  subsets: ['latin'],
  variable: '--font-body',
});

const sairaStencil = Saira_Stencil_One({
  weight: ['400'],
  subsets: ["latin"],
  variable: "--font-saira-stencil"
});

const saira = Saira({
  weight: ['400'],
  subsets: ["latin"],
  variable: "--font-saira"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          `
          ${fontTitle.variable} 
          ${fontBody.variable} 
          ${sairaStencil.variable}
          ${geistSans.variable} 
          ${saira.variable}
          ${geistMono.variable} 
          antialiased
          `
        }
      >
        <AuthProvider>
          <CartProvider>
            <Toaster 
              duration={3000}
              position="top-right"
            />
            <Header />
            {children}
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
